server:
  port: 8081
  error:
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:mysql://cis9cbtgerlk68wl.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/kfbvr88i3ssk0zjc
    username: xh1hgkisvc0puesp
    password: w6ok46y5eiyk6znv
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
url:
  api: https://user-info.herokuapp.com/
